@host = http://localhost:3000



###
POST {{host}}/register
Content-Type: application/json

{
    "name":"Akash",
    "email":"dakash682@gmail.com",
    "password":"pass123"
}

###
POST {{host}}/login
Content-Type: application/json

{
    "email":"dakash682@gmail.com",
    "password":"pass123"
}



###
POST {{host}}/verify_otp
Content-Type: application/json

{
    "email":"dakash682@gmail.com",
    "otp":"848434"
}


###
POST {{host}}/resend_otp
Content-Type: application/json

{
    "email":"dakash682@gmail.com"
}
// make sure the id token is correct


###
GET {{host}}/students
Content-Type: application/json

{
    "token":"sdfsdsdsdf"
}

